### ISSUE TITLE
add boot-disk-size option on instance creation

### ISSUE THREAD

**Issue by ggrasso** [GoogleCloudPlatform/bdutil#14]
The script creates instances with default boot disk size(10GB), but there is no env variable to modify this value.
It would be handy to add the option 
--boot-disk-size=${DISK_BOOT_SIZE_GB} 
in the function create_cluster

**Comment by dennishuo** [comment]
One tricky bit to keep in mind is that since the boot disk is created on-demand from machine images, even if the boot disk is increased in size, the _visible_ size will remain at 10GB until fdisk is used to either resize the root partition or to add a new partition, and then the VM is rebooted. In fact, there are two options:
1. Use fdisk to just add a second partition on the boot disk without touching the root partition, this can be combined with some careful usage of partprobe to update in-place, possibly without requiring a reboot; still need extra work to format and mount the new partition. The downside is that since it's a separate partition, it feels a lot like just adding a separate attached disk, without the same benefits of allow flexibility in keeping it as a separate disk on turndown.
2. Use fdisk to actually [resize the root partition, reboot, then resize2fs](https://cloud.google.com/compute/docs/disks/persistent-disks#repartitionrootpd). The reboot is suboptimal, though there are some tricks for being able to resize even the root partition in-place. We haven't recently investigated the resize-in-place approach.

bdutil isn't great right now at orchestrating command steps which span over reboots, but in theory it could work fine if reboot is the last step that bdutil runs, possibly launched in the background with "nohup" and a short delay so allow bdutil's SSH session to complete normally.

**Comment by ggrasso** [comment]
Thank you for this valuable information. In my case I'm using ubuntu images which seems to support autoresizing, but in general I get your point. However having the option to set the boot-disk-size as env variable will not affect those cases where resizing is anyway necessary as you correclty point out, but would be an improvement to allow usage of instances with autoresize (like in my case).
