### ISSUE TITLE
bdutil ./hadoop-validate-setup.sh - MAPRED job stuck

### ISSUE THREAD

**Issue by blogmaniak** [GoogleCloudPlatform/bdutil#34]
I have been struggling with getting the bdutil based gce master only server to run mapred jobs.
./bdutil deploy -e hadoop2_env.sh --bucket anintelcluster -n 0 -P anintelcluster
Above command sets up the hadoop2 on the master server, i can see the yarn page.
However, once I run the hadoop validate command, the job gets stuck.
15/06/23 18:58:34 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.0-hadoop2
15/06/23 18:58:36 INFO client.RMProxy: Connecting to ResourceManager at anintelcluster-m/10.240.98.45:8032
15/06/23 18:58:38 INFO terasort.TeraSort: Generating 100000 using 0
15/06/23 18:58:40 INFO mapreduce.JobSubmitter: number of splits:0
15/06/23 18:58:41 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1435085683024_0001
15/06/23 18:58:42 INFO impl.YarnClientImpl: Submitted application application_1435085683024_0001
15/06/23 18:58:42 INFO mapreduce.Job: The url to track the job: http://anintelcluster-m:8088/proxy/application_1435085683024_0001/
15/06/23 18:58:42 INFO mapreduce.Job: Running job: job_1435085683024_0001

**Comment by dennishuo** [comment]
Setting "-n 0" isn't normally sufficient to get a master-only setup; does it still get stuck if you try it with the following?:

```
./bdutil deploy -e hadoop2_env.sh --bucket anintelcluster -e single_node_env.sh -P anintelcluster
```

**Comment by blogmaniak** [comment]
awesome, that worked - i can keep digging.
However, i eventually need to deploy a cluster with at least 3 datanodes with spark running in parallal to hadoop. Last time I tried the following command ./bdutil deploy -e hadoop2_env.sh --bucket anintelcluster -n 2 -P anintelcluster --env_var_files spark_env.sh.

Will this command set things up properly, or should I use a different variant?

**Comment by dennishuo** [comment]
That should work, except that when using non-single-node clusters, the datanodes only run on the workers and not the master; you can optionally specify a smaller master with the [--master_machine_type flag](https://github.com/GoogleCloudPlatform/bdutil/blob/master/bdutil#L75), and then use "-n 3" if you really want three workers.

Note that in this mode, it indeed turns up a separate "Spark standalone" setup parallel to Hadoop, which is permitted to overstep its memory/CPU usage such that if you use Spark very heavily at the same time as running MapReduce on YARN, they may cause memory issues for each other. However, it should be fine if you only use one or the other at a time, and/or keep resource usage lower.

The way to get Spark to "play nice" with other Hadoop jobs is to put it all on YARN, though Spark startup overhead takes a performance penalty. In that case, you'd want to use:

```
./bdutil deploy --bucket anintelcluster -n 2 -P anintelcluster -e extensions/spark/spark_on_yarn_env.sh
```

instead of adding hadoop2_env.sh and spark_env.sh separately; spark_on_yarn_env.sh will automatically import hadoop2_env.sh as a base, but will also additionally do configuration to make the default Spark master be "yarn-client".

**Comment by dennishuo** [comment]
Marking as closed, since it sounds like the single_node_env.sh worked; feel free to ping or reopen if you run into issues again.

**Comment by blogmaniak** [comment]
Thank you - I am able to setup and run spark jobs on gce cluster now.
